/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as TasksRouteRouteImport } from './routes/tasks/route'
import { Route as SharedRouteRouteImport } from './routes/shared/route'
import { Route as NotesRouteRouteImport } from './routes/notes/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as SharedUserIdRouteImport } from './routes/shared/$userId'
import { Route as NotesNewRouteImport } from './routes/notes/new'
import { Route as DashboardStatsRouteImport } from './routes/dashboard/stats'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRouteRoute = TasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRouteRoute = SharedRouteRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRouteRoute = NotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRouteRoute,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TasksRouteRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRouteRoute,
} as any)
const SharedUserIdRoute = SharedUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => SharedRouteRoute,
} as any)
const NotesNewRoute = NotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NotesRouteRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/notes': typeof NotesRouteRouteWithChildren
  '/shared': typeof SharedRouteRouteWithChildren
  '/tasks': typeof TasksRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedules': typeof SchedulesRoute
  '/stats': typeof StatsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/notes/new': typeof NotesNewRoute
  '/shared/$userId': typeof SharedUserIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shared': typeof SharedRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedules': typeof SchedulesRoute
  '/stats': typeof StatsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/notes/new': typeof NotesNewRoute
  '/shared/$userId': typeof SharedUserIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/notes': typeof NotesIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/notes': typeof NotesRouteRouteWithChildren
  '/shared': typeof SharedRouteRouteWithChildren
  '/tasks': typeof TasksRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedules': typeof SchedulesRoute
  '/stats': typeof StatsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/notes/new': typeof NotesNewRoute
  '/shared/$userId': typeof SharedUserIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/notes'
    | '/shared'
    | '/tasks'
    | '/agenda'
    | '/login'
    | '/profile'
    | '/register'
    | '/schedules'
    | '/stats'
    | '/dashboard/stats'
    | '/notes/new'
    | '/shared/$userId'
    | '/tasks/$id'
    | '/tasks/new'
    | '/dashboard/'
    | '/notes/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shared'
    | '/agenda'
    | '/login'
    | '/profile'
    | '/register'
    | '/schedules'
    | '/stats'
    | '/dashboard/stats'
    | '/notes/new'
    | '/shared/$userId'
    | '/tasks/$id'
    | '/tasks/new'
    | '/dashboard'
    | '/notes'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/notes'
    | '/shared'
    | '/tasks'
    | '/agenda'
    | '/login'
    | '/profile'
    | '/register'
    | '/schedules'
    | '/stats'
    | '/dashboard/stats'
    | '/notes/new'
    | '/shared/$userId'
    | '/tasks/$id'
    | '/tasks/new'
    | '/dashboard/'
    | '/notes/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  NotesRouteRoute: typeof NotesRouteRouteWithChildren
  SharedRouteRoute: typeof SharedRouteRouteWithChildren
  TasksRouteRoute: typeof TasksRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SchedulesRoute: typeof SchedulesRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRouteRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof TasksRouteRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRouteRoute
    }
    '/shared/$userId': {
      id: '/shared/$userId'
      path: '/$userId'
      fullPath: '/shared/$userId'
      preLoaderRoute: typeof SharedUserIdRouteImport
      parentRoute: typeof SharedRouteRoute
    }
    '/notes/new': {
      id: '/notes/new'
      path: '/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewRouteImport
      parentRoute: typeof NotesRouteRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface NotesRouteRouteChildren {
  NotesNewRoute: typeof NotesNewRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteRouteChildren: NotesRouteRouteChildren = {
  NotesNewRoute: NotesNewRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteRouteWithChildren = NotesRouteRoute._addFileChildren(
  NotesRouteRouteChildren,
)

interface SharedRouteRouteChildren {
  SharedUserIdRoute: typeof SharedUserIdRoute
}

const SharedRouteRouteChildren: SharedRouteRouteChildren = {
  SharedUserIdRoute: SharedUserIdRoute,
}

const SharedRouteRouteWithChildren = SharedRouteRoute._addFileChildren(
  SharedRouteRouteChildren,
)

interface TasksRouteRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
  TasksNewRoute: typeof TasksNewRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteRouteChildren: TasksRouteRouteChildren = {
  TasksIdRoute: TasksIdRoute,
  TasksNewRoute: TasksNewRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteRouteWithChildren = TasksRouteRoute._addFileChildren(
  TasksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  NotesRouteRoute: NotesRouteRouteWithChildren,
  SharedRouteRoute: SharedRouteRouteWithChildren,
  TasksRouteRoute: TasksRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SchedulesRoute: SchedulesRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
