package db

import (
	"testing"
	"time"
)

// One-off tasks (repeating=false with an explicit StartDate) must materialize on
// their StartDate, respecting StartTime — not on time.Now().
func TestGetNextTaskDate_OneOffUsesStartDate(t *testing.T) {
	startDate := date(2026, 8, 15) // distinct from today
	st := &ScheduleTask{
		Repeating: false,
		Frequency: ScheduleTaskFrequencyCustom,
		StartDate: startDate,
		StartTime: time.Date(2000, 1, 1, 10, 30, 0, 0, time.Local),
	}

	got, err := getNextTaskDate(st)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if got.Year() != 2026 || got.Month() != time.August || got.Day() != 15 {
		t.Fatalf("expected materialization on 2026-08-15, got %s", got.Format("2006-01-02"))
	}
	if got.Hour() != 10 || got.Minute() != 30 {
		t.Fatalf("expected time 10:30, got %02d:%02d", got.Hour(), got.Minute())
	}

	now := time.Now()
	if got.Year() == now.Year() && got.Month() == now.Month() && got.Day() == now.Day() {
		t.Fatal("one-off must NOT land on time.Now()")
	}
}

func TestGetNextTaskDate_OneOffWithoutStartTime(t *testing.T) {
	st := &ScheduleTask{
		Repeating: false,
		Frequency: ScheduleTaskFrequencyCustom,
		StartDate: date(2026, 8, 15),
	}

	got, err := getNextTaskDate(st)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got.Year() != 2026 || got.Month() != time.August || got.Day() != 15 {
		t.Fatalf("expected 2026-08-15, got %s", got.Format("2006-01-02"))
	}
	if got.Hour() != 0 || got.Minute() != 0 {
		t.Fatalf("expected midnight, got %02d:%02d", got.Hour(), got.Minute())
	}
}

// Recurring tasks must keep the existing scheduling logic — the one-off branch
// must not steal their StartDate.
func TestGetNextTaskDate_RecurringUnaffected(t *testing.T) {
	st := &ScheduleTask{
		Repeating:       true,
		RepeatFrequency: ScheduleTaskRepeatFrequencyDaily,
		StartDate:       date(2026, 8, 15),
	}

	got, err := getNextTaskDate(st)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// Daily recurring resolves relative to now, never to the far StartDate.
	if got.Year() == 2026 && got.Month() == time.August && got.Day() == 15 {
		t.Fatal("recurring task must not materialize on its StartDate")
	}
}

// A one-off with frequency "custom" must NOT be regenerated by the lazy day
// generator, so it never duplicates on the selected date nor leaks onto today.
func TestShouldCreateTaskForToday_OneOffCustomNotRegenerated(t *testing.T) {
	st := &ScheduleTask{
		Repeating: false,
		Frequency: ScheduleTaskFrequencyCustom,
		StartDate: date(2026, 8, 15),
	}
	if shouldCreateTaskForToday(st, date(2026, 8, 15)) {
		t.Fatal("custom one-off must not be regenerated by lazy day generation")
	}
	if shouldCreateTaskForToday(st, date(2026, 8, 16)) {
		t.Fatal("custom one-off must not appear on other days")
	}
}
